### PR TITLE
Handle WebMeUp bots (BLEXBot)

### PR DESCRIPTION
**Pull request by gabrieljablonski**
BLEXBot is a crawler that is responsible for a good chunk of bot requests on a website I manage (>200k requests over multiple IPs), so handling it with legitbot seems like a good idea.

The bot specs are available here: http://webmeup-crawler.com/

Let me know if any changes are needed.

### CODE REVIEW

**Comment by gabrieljablonski** [comment]
Btw, sorry for spamming PRs.

I'm going over some IP addresses that are littering user tracking in my project, so I'm submitting for each of the top crawler bots that aren't already covered by `legitbot`. Should be only 1 or 2 more left after this one.

**Comment by alaz** [comment]
> Btw, sorry for spamming PRs.

No, no, your PRs are perfect. I do prefer to have separate commits for bots.

**Review by alaz — APPROVED** [review]
LGTM

**Comment by alaz** [comment]
> This should be the last one for now

I am a bit tied up at the moment, but will make a release this weekend latest.

**Comment by gabrieljablonski** [comment]
>I am a bit tied up at the moment, but will make a release this weekend latest.

No worries. Thanks for taking a look so quickly!

**Pull request merged**
