### PR TITLE
"interval_tree" instead of "segment_tree"

### PR DESCRIPTION
**Pull request by alaz**

### CODE REVIEW

**Comment by alaz** [comment]
@kirichkov could you please review. Are there any other test cases you would like to cover?

**Comment by alaz** [comment]
Do you want me to release?

**Comment by kirichkov** [comment]
> Do you want me to release?

Yes, please. Unless you want me to point at that branch and drop it into production and see how it works in the real world :-)

**Comment by alaz** [comment]
OK, I am releasing then.

**Comment by kirichkov** [comment]
So far so good. No false positives!

**Comment by alaz** [comment]
Great! 👍

**Pull request merged**
